debug: true
  # DEVTOOLS
spring:
  devtools:
    livereload:
      enabled: true # Enable a livereload.com compatible server.
      port: 35729 # Server port.
    restart:
      additional-exclude:  # Additional patterns that should be excluded from triggering a full restart.
      additional-paths:  # Additional paths to watch for changes.
      enabled: true # Enable automatic restart.
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties # Patterns that should be excluded from triggering a full restart.
      poll-interval: 1000 # Amount of time (in milliseconds) to wait between polling for classpath changes.
      quiet-period: 400 # Amount of quiet time (in milliseconds) required without any classpath changes before a restart is triggered.
      trigger-file: # Name of a specific file that when changed will trigger the restart check. If not specified any classpath file change will trigger the restart.

  # TLS , port 587
  #spring.mail.properties.mail.smtp.starttls.enable=true
  # SSL, post 465
  #spring.mail.properties.mail.smtp.socketFactory.port = 465
  #spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
  #server:
  #port: 8082
